name: windows-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-msix:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e ".[dev]"
      - name: Run tests
        run: pytest -q
      - name: Build exe with PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller --onefile --name lrc.exe src/lrc/cli.py
          mkdir dist\lrc-win
          move .\dist\lrc.exe dist\lrc-win\lrc.exe
      - name: Install Windows 10 SDK tools
        shell: powershell
        run: |
          choco install windows-sdk-10.1 -y
          $env:PATH += ";C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64"
      - name: Pack MSIX (unsigned)
        shell: powershell
        run: |
          .\packaging\msix\make_msix.ps1 -BuildDir "dist\lrc-win" -Out "LRC-App-unsigned.msix"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LRC-MSIX-unsigned
          path: LRC-App-unsigned.msix
